# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    user_provider:
        class: AppBundle\Security\UserProvider
        arguments: ["@doctrine.orm.entity_manager"] 
        
        
    security.user_voter:
     class:      AppBundle\Security\Authorization\Voter\UserVoter
     public:     false
     arguments: ["@service_container"] 
     tags:
        - { name: security.voter }
        
    
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
