<?php

namespace AppBundle\Entity;

use AppBundle\Entity\BaseRepository;

/**
 * StatusyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusyRepository extends BaseRepository
{
    protected static $alias = 'statusy';
    protected static $entity = 'AppBundle:Statusy';
}
